### ISSUE TITLE
Ionic/Angular Router fix for dotnet backend or universal backend

### ISSUE THREAD

**Issue by frostyandy2k** [ScaleIT-Org/sapp-ionic-dotnetcore-example#1]
We want to avoid this (index.html# prefix):

http://localhost:5050/index.html#/admin

**Comment by fridaypatrick** [comment]
This feature will be released in Ionic v4
https://github.com/ionic-team/ionic/issues/10565#issuecomment-355055546

Closing this as this will require a migration to the next version after it gets released
